server:
  applicationConnectors:
  - type: http
    port: ${DW_PORT:-9000}
  adminConnectors:
  - type: http
    port: ${DW_ADMIN_PORT:-9100}
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ./logs/robust-acccess.log
        # Rolled over daily and retained for 30 days.
        archivedLogFilenamePattern: ./logs/robust-access-%d.log.gz
        archivedFileCount: 30
        logFormat: "%-5level [RequestID: %X{requestID}] [%date] [%thread] %logger %message%n"

httpClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  retries: 5
  keepAlive: 5000ms


pingerHost: http://localhost:7999

logging:
  level: INFO

  loggers:
    no.bekk.distsys: DEBUG

  appenders:
    - type: console
      target: stdout
      timeZone: CEST
      logFormat: "%-5level [%date] [%thread] %logger %message%n"
    # Log debug messages, info, warnings and errors to our apps' debug log.
    # Rolled over hourly and retained for 6 hours
    - type: file
      currentLogFilename: ./logs/robust-debug.log
      archivedLogFilenamePattern: ./logs/robust-debug-%d{yyyy-MM-dd-hh}.log.gz
      archivedFileCount: 6
      logFormat: "%-5level [RequestID: %X{requestID}] [%date] [%thread] %logger %message%n"

