server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9100
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ./logs/robust-acccess.log
        # Rolled over daily and retained for 30 days.
        archivedLogFilenamePattern: ./logs/robust-access-%d.log.gz
        archivedFileCount: 30
        logFormat: "%-5level [RequestID: %X{requestID}] [%date] [%thread] %logger %message%n"

httpClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  retries: 5
  keepAlive: 5000ms


consul:
  # Optional properties
  # endpoint for consul (defaults to localhost:8500)
  endpoint: localhost:8500
  # service port
  servicePort: 9000
  # service time to live
  serviceTTL: 30 seconds
  # check interval frequency
  checkInterval: 1 second


pingerHost: http://localhost:7999

logging:
  level: INFO

  loggers:
    no.bekk.distsys: DEBUG

  appenders:
    - type: console
      target: stdout
      timeZone: CEST
      logFormat: "%-5level [RequestID: %X{requestID}] [%date] [%thread] %logger %message%n"
    # Log debug messages, info, warnings and errors to our apps' debug log.
    # Rolled over hourly and retained for 6 hours
    - type: file
      currentLogFilename: ./logs/robust-debug.log
      archivedLogFilenamePattern: ./logs/robust-debug-%d{yyyy-MM-dd-hh}.log.gz
      archivedFileCount: 6
      logFormat: "%-5level [RequestID: %X{requestID}] [%date] [%thread] %logger %message%n"

    # Log info, warnings and errors to local logstash instance through udp
    #  won't fail if logstash is not running
#    - type: logstash-socket
#      threshold: INFO
#      host: 127.0.0.1
#      port: 9001
#      includeMdc: true
#      customFields:
#        application: tl_auth # change accordingly
